name: Build Apps

on:
  push:
    branches:
      - main

jobs:
  build-android-app:
    name: Build Android App
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: echo ${{ secrets.DOT_ENV_BASE64 }} | base64 --decode > .env

      - name: Create google-services.json
        run: echo ${{ secrets.GOOGLE_SERVICE_JSON_BASE64 }} | base64 --decode > ./android/app/google-services.json

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          channel: stable
          flutter-version: 3.29.3

      - name: Install packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
