name: Build

on:
    push:
      branches:
        - main

jobs:
  android:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.0.3"

      - name: Create secret file
        run: >
          deno run \
            --allow-read=. \
            --allow-write=. \
            .github/createSecret.ts \
            --FIREBASE_ANDROID_API_KEY ${{ secrets.FIREBASE_ANDROID_API_KEY }} \
            --FIREBASE_IOS_API_KEY ${{ secrets.FIREBASE_IOS_API_KEY }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: "3.24.3"

      - name: Install packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
