name: Build

on:
    push:
      branches:
        - main

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.38.0"

      - name: Create .env
        run: >
            deno run --allow-write=. .github/createEnviron.ts
            --BSAM_SERVER_URL ${{ secrets.BSAM_SERVER_URL }}
            --BSAM_SERVER_TOKEN ${{ secrets.BSAM_SERVER_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.10.4"

      - name: Install packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
