name: Check quality

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.38.0"

      - name: Create dummy .env
        run: >
            deno run --allow-write=. .github/createEnviron.ts
            --BSAM_SERVER_URL wss://example.com
            --BSAM_SERVER_TOKEN secret

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.10.4"

      - name: Install packages
        run: flutter pub get

      - name: Lint
        run: flutter analyze
