name: Check and test the source code

on:
  push:
    branches:
      - main
      - v4-develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.10.2'

      - name: Install packages
        run: flutter pub get

      - name: Lint
        run: flutter analyze

      - name: Test
        run: flutter test
